[package]
name = "rk"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.13.2"
serde = { version = "1.0.228", features = ["derive"]}
toml = "0.9.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
