# rk configuration file
# Place in: ./rk.toml, ~/.config/rk.toml, or /etc/rk.toml
# Or set `RK_CONFIG=/path/to/config.toml`

# Check https://docs.rs/evdev/latest/evdev/struct.Key.html for a reference of key names
# Keys can be written like: "w", "W", or "KEY_W" (case insensitive)

# Can be a single key: "f12" or a combination: "ctrl+enter"
toggle = "leftctrl+grave"

# Default mappings (always active when remapper is enabled)
[mappings.default]
w = "up"
a = "left"
s = "down"
d = "right"

# Conditional mappings based on LED states
[mappings.numlock_off]
q = "kp7" # numpad 7 (up-left)
e = "kp9" # numpad 9 (up-right)
z = "kp1" # numpad 1 (down-left)
c = "kp3" # numpad 3 (down-right)

# Multiple conditions can be chained
#[mappings.numlock_off.capslock_on]
#w = "up"
